project:
  type: website
  output-dir: docs

website:
  title: "DeepLearning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  draft-mode: visible

format:
  html:
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: false
    theme: cosmo
    highlight-style: github
    css: styles.css
    collapsible: true